Parallelize MTX generation (#86)
DailyDreaming/load-project pull request #104
Opened 2020-01-15 19:12 UTC by danielsotirhos

Ticket https://github.com/DailyDreaming/load-project/issues/86

2020-01-16 20:32 UTC, hannes-ucsc requested changes
Remove all changes not essential to concurrency. Associate errors in worker threads with the GEO project and report projects with any errors, those raised in the main thread as well as those raised in worker threads.

2020-01-16 20:32 UTC, hannes-ucsc commented on csv2mtx.py
> +# from tqdm import tqdm
-

2020-01-16 20:32 UTC, hannes-ucsc commented
Use a log formatter to add thread name to all log messages.

2020-01-17 19:58 UTC, danielsotirhos commented
Rebased onto latest master.
Assigning to @hannes-ucsc for remaining todo: handle exceptions in threads.

2020-01-21 06:24 UTC, merged