Create symlinks to project folders
DailyDreaming/load-project pull request #11
Opened 2019-12-18 22:50 UTC by GPelayo

2019-12-18 23:05 UTC, dsotirho-ucsc requested changes

2019-12-18 23:05 UTC, danielsotirhos commented on download_geo_matrix.py
> +    os.symlink(projects_subdirectory, file_link_path)
The symlink should point to the uuid folder, not to the 'geo' subfolder inside it.
```suggestion
    os.symlink(f'projects/{deterministic_uuid}', file_link_path)
```

2019-12-18 23:58 UTC, dsotirho-ucsc approved these changes

2019-12-19 05:33 UTC, hannes-ucsc approved these changes

2019-12-19 05:33 UTC, hannes-ucsc commented on download_geo_matrix.py
> +    if not os.path.exists(save_file_path):
Isn't this redundant with `exist_ok=True`?

2019-12-19 05:33 UTC, merged