Replace latin-1 characters so that gene names are consistent
DailyDreaming/load-project pull request #136
Opened 2020-01-22 22:43 UTC by achave11

2020-01-22 22:47 UTC, danielsotirhos commented
Ticket https://github.com/DailyDreaming/load-project/issues/114

2020-01-22 22:56 UTC, danielsotirhos commented on convert_matrices.py
> +            row[0] = gene.replace('\x94', '')
```suggestion
            row[0] = row[0].replace('\x93', '').replace('\x94', '')
```

2020-01-22 22:57 UTC, dsotirho-ucsc approved these changes
`.replace()` can be chained to avoid creating temp variable `gene`.
Other than that it looks good to me.

2020-01-23 05:31 UTC, hannes-ucsc requested changes

2020-01-23 05:31 UTC, hannes-ucsc commented on convert_matrices.py
> +        if row[0].startswith('\x93') or row[0].endswith('\x94'):
Are you sure that the only occurrences of these characters is at the beginning or end of a cell?

Are you sure that they only occur in the first column?

If the answer to either to both of these is yes, start thinking about how you can optimize statements: For example, if you know a character occurs at the beginning of a string, do you really need to scan the entire string? Same with the end. If the argument to startswith() is a single character string, can you optimize that expression?

If then answer to either of these question is no, we need to rethink this approach.

2020-01-23 05:31 UTC, hannes-ucsc commented on convert_matrices.py
> +            **self.kwargs)
Wouldn't this fail if kwargs is the default value of None? Did you test this for any projects other than the one with the latin1-encoded file?

2020-01-23 05:31 UTC, hannes-ucsc commented on convert_matrices.py
> +            **self.kwargs)
Anyhow, I'm not a fan of the wholesale kwargs pass-though. Please just add an `encoding` field instead.

2020-01-24 02:49 UTC, hannes-ucsc approved these changes

2020-01-24 02:50 UTC, merged

2020-01-24 02:50 UTC, hannes-ucsc commented
I'll run `make matrices` on  GSE127969 shortly.