Add overview report (#82)
DailyDreaming/load-project pull request #84
Opened 2020-01-12 04:33 UTC by danielsotirhos

2020-01-12 04:34 UTC, danielsotirhos commented
For #82

2020-01-13 21:17 UTC, hannes-ucsc requested changes
It would be more flexible if this wrote to stdout. See also my suggestion on the make file.

2020-01-13 21:17 UTC, hannes-ucsc commented on overview_report.py
> +            'Accession ID',
```suggestion
            'accession',
```

Accessions *are* identifiers.

2020-01-13 21:17 UTC, hannes-ucsc commented on overview_report.py
> +            'Project path',
```suggestion
            'project_path',
```

2020-01-13 21:17 UTC, hannes-ucsc commented on overview_report.py
> +            'Accession symlink',
```suggestion
            'symlink',
```

2020-01-13 21:17 UTC, hannes-ucsc commented on overview_report.py
> +            'Geo files count',
```suggestion
            'geo_files',
```

2020-01-13 21:17 UTC, hannes-ucsc commented on overview_report.py
> +            'UUID',
```suggestion
            'uuid',
```

2020-01-13 21:17 UTC, hannes-ucsc commented on overview_report.py
> +            'Spreadsheet',
```suggestion
            'spreadsheet',
```

2020-01-13 21:17 UTC, hannes-ucsc commented on overview_report.py
> +            'Matrices count',
```suggestion
            'num_matrices',
```

2020-01-13 21:17 UTC, hannes-ucsc commented on overview_report.py
> +            'Zipped matrix',
```suggestion
            'zipped_matrix',
```

2020-01-13 21:17 UTC, hannes-ucsc commented on overview_report.py
> +            'Cell count',
```suggestion
            'cell_count',
```

2020-01-13 21:17 UTC, hannes-ucsc commented on overview_report.py
> +            'Metadata JSON count',
```suggestion
            'num_metadata_files',
```

2020-01-13 21:17 UTC, hannes-ucsc commented on Makefile
> +	python3 overview_report.py
```suggestion
	python3 overview_report.py | column -nt | less -S
```

2020-01-14 01:13 UTC, hannes-ucsc approved these changes

2020-01-14 01:16 UTC, merged